name: Daily Tibia XP Tracker

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:     # Manual trigger support

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper script
        run: python scrape_xp.py
